### ISSUE TITLE
Where can I ask questions about these examples?

### ISSUE THREAD

**Issue by reselbob** [solana-developers/program-examples#57]
Hi:

I am trying to understand the examples in this repo. While I have reasonable understanding of writing Solidity code for EVM targets, some of the code in the examples is hard for me to understand. For example, in this:

```
@program_id("F1ipperKF9EfD821ZbbYjS319LXYiBmjhzkkf5a26rC")
contract hello_solana {
    // The constructor is used to create a new account
    // Here we create a new account that stores no data and only prints messages to the program logs when the constructor is called.
    @payer(payer) // The "payer" pays for the account creation
    constructor() {
        // We get the program ID by calling 'this';
        address programId = address(this);

        // Print messages to the program logs
        print("Hello, Solana!");
        print("Our program's Program ID: {:}".format(programId));
    }
}
```

What is the meaning of `@program_id` and how is the value `F1ipperKF9EfD821ZbbYjS319LXYiBmjhzkkf5a26rC` generated or discovered?

Also, what is  `@payer(payer)` about? I have not run across this before in typical Solidity programming for the EVM.

I know these are newbie questions, maybe not appropriate for this issue. If so, please might you be able to tell me where I can get some questions answered?

Thanks in advance!

**Comment by ZYJLiu** [comment]
Hello! Solang enables the ability to write Solana programs using Solidity, however, the details for building are more closely related to Solana development rather than those for EVM contracts. While the syntax may appear similar, the underlying principles and functionalities are more strongly tied to Solana. This is a bit confusing, but don't worry!

The `@program_id` is the on-chain address of the contract (on Solana smart contracts are commonly referred to as "programs").

If you created a solang project using the [Anchor framework](https://github.com/coral-xyz/anchor) with the `--solidity` flag:
```
 anchor init [project-name] --solidity
```

Then you can run the command `anchor keys list` which will return the value to update `@program_id`.
The keypair that was generated can then be found in `/target/deploy/[project-name]-keypair.json`
```
johnliu@Johns-MacBook-Pro solang-example % anchor keys list
solang_example: US8pF3WanpLidAWaLHSeexNSXdGrmmXDqdMXhD6YaoR
```

`@payer(payer)` annotation specifies a Solana account that is going to pay (allocate some amount of SOL) for the initialization of the contract’s data account. This relates to the concept of Solana's Account Model where a program's logic and state are separate. Here is an article by [Helius](https://www.helius.dev/blog/the-solana-programming-model-an-introduction-to-developing-on-solana#what-are-accounts) that goes over some common concepts for developing on Solana. 

The [solana stack exchange](https://solana.stackexchange.com/) is also a resource for questions related to building on Solana!

**Comment by reselbob** [comment]
Thank you @ZYJLiu !

**Comment by nickfrosty** [comment]
Closing since the question was answered
